// MarketRead — paragraph tile above the hero, with typewriter reveal.
//
// The market read text streams in character-by-character on first render and
// after every refresh — same effect as a ChatGPT response being written.
// Reinforces that the paragraph is genuinely AI-generated, not a static tile.

const Typewriter = ({ text, speed = 18, onDone }) => {
  const [shown, setShown] = React.useState(0);

  React.useEffect(() => {
    setShown(0);
    if (!text) return;
    let i = 0;
    const interval = setInterval(() => {
      i += 1;
      setShown(i);
      if (i >= text.length) {
        clearInterval(interval);
        if (onDone) onDone();
      }
    }, speed);
    return () => clearInterval(interval);
  }, [text, speed]);

  const visible = (text || "").slice(0, shown);
  const done = !text || shown >= text.length;

  return (
    <>
      {visible}
      {!done && (
        <span
          aria-hidden="true"
          style={{
            display: "inline-block",
            width: 8,
            height: 18,
            marginLeft: 2,
            verticalAlign: "-3px",
            background: "var(--fg-muted)",
            animation: "tilt-caret-blink 1s steps(2) infinite",
          }}
        />
      )}
    </>
  );
};

const MarketRead = ({ data }) => {
  // Parse snapshot_date as-is. Some API responses give "—" when no data.
  let dateStr = "—";
  try {
    if (data.snapshot_date && data.snapshot_date !== "—") {
      dateStr = new Date(data.snapshot_date + "T09:30:00").toLocaleDateString("en-IN", {
        day: "numeric",
        month: "long",
        year: "numeric",
      });
    }
  } catch (e) {
    dateStr = data.snapshot_date || "—";
  }
  const { tickers_scanned = 0, total_picks = 0, lane_counts = {} } = data.scan_stats || {};
  const isGemini = data.llm_provider === "gemini";

  return (
    <section
      style={{
        background: "var(--bg-elev)",
        borderRadius: 12,
        padding: "26px 32px 22px",
        marginBottom: 24,
        position: "relative",
        overflow: "hidden",
      }}
    >
      <div
        style={{
          position: "absolute", top: -120, left: -120, width: 300, height: 300,
          background: "radial-gradient(circle, rgba(167,139,250,0.10), transparent 70%)",
          pointerEvents: "none",
        }}
      />
      <header
        style={{
          display: "flex", justifyContent: "space-between", alignItems: "baseline",
          marginBottom: 14, flexWrap: "wrap", gap: 8,
        }}
      >
        <div style={{ display: "flex", alignItems: "center", gap: 10, flexWrap: "wrap" }}>
          <div
            style={{
              fontFamily: "'JetBrains Mono', monospace",
              fontSize: 10.5, letterSpacing: 1.4, textTransform: "uppercase",
              color: "var(--fg-muted)",
            }}
          >
            Market Read · {dateStr}
          </div>
          {isGemini && (
            <span
              title="Generated by Gemini, grounded on real indicator values"
              style={{
                fontFamily: "'JetBrains Mono', monospace",
                fontSize: 10, letterSpacing: 1.2, textTransform: "uppercase",
                color: "#A78BFA",
                padding: "3px 8px",
                border: "1px solid rgba(167,139,250,0.4)",
                background: "rgba(167,139,250,0.08)",
                borderRadius: 999,
              }}
            >
              ✦ ai-written
            </span>
          )}
        </div>
        <div
          style={{
            fontFamily: "'JetBrains Mono', monospace",
            fontSize: 10.5, color: "var(--fg-muted)",
            display: "flex", alignItems: "center", gap: 6,
          }}
        >
          <span style={{
            width: 6, height: 6, borderRadius: 999, background: "#22D3A4",
            boxShadow: "0 0 8px #22D3A488",
          }} />
          {(data.data_mode || "—").toUpperCase()}
        </div>
      </header>

      <p
        style={{
          fontSize: 16, lineHeight: 1.6, color: "var(--fg)",
          margin: 0, maxWidth: 760, minHeight: 80, textWrap: "pretty",
        }}
      >
        <Typewriter text={data.market_read || ""} speed={14} />
      </p>

      <footer
        style={{
          marginTop: 18, paddingTop: 14,
          borderTop: "1px solid var(--border)",
          display: "flex", gap: 28, flexWrap: "wrap",
          fontFamily: "'JetBrains Mono', monospace",
          fontSize: 11, color: "var(--fg-muted)",
        }}
      >
        <ScanStat label="Scanned" value={tickers_scanned} />
        <ScanStat label="Picks" value={total_picks} />
        <span style={{ color: "var(--border-strong)" }}>·</span>
        <ScanStat label="Strong" value={lane_counts.strong || 0} color="#22D3A4" />
        <ScanStat label="Momentum" value={lane_counts.momentum || 0} color="#7DD3FC" />
        <ScanStat label="Value" value={lane_counts.value || 0} color="#FBBF24" />
        <ScanStat label="Smart Money" value={lane_counts.smart_money || 0} color="#A78BFA" />
      </footer>
    </section>
  );
};

const ScanStat = ({ label, value, color }) => (
  <span style={{ display: "inline-flex", gap: 8, alignItems: "baseline" }}>
    <span style={{ color: "var(--fg-faint)", textTransform: "uppercase", letterSpacing: 0.8, fontSize: 10 }}>
      {label}
    </span>
    <span style={{ color: color || "var(--fg)", fontWeight: 600 }}>{value}</span>
  </span>
);

window.MarketRead = MarketRead;
window.Typewriter = Typewriter;
