// TopNav — minimal app chrome (logo, date pill, refresh, theme toggle).
const TopNav = ({
  snapshotDate,
  dark,
  onToggleTheme,
  onRefresh,
  refreshing,
  llmProvider,
  dataMode,
}) => {
  const { Icon } = window;
  const isGemini = llmProvider === "gemini";
  const isSnapshot = dataMode === "snapshot";
  return (
    <nav
      style={{
        display: "flex", justifyContent: "space-between", alignItems: "center",
        padding: "16px 32px",
        borderBottom: "1px solid var(--border)",
        background: "var(--bg)",
        position: "sticky", top: 0, zIndex: 50,
        backdropFilter: "blur(6px)",
      }}
    >
      <div style={{ display: "flex", alignItems: "center", gap: 16 }}>
        <Logo />
        <span
          style={{
            fontFamily: "'JetBrains Mono', monospace",
            fontSize: 10, letterSpacing: 1.2, textTransform: "uppercase",
            color: "var(--fg-faint)",
            padding: "4px 10px",
            border: "1px solid var(--border)",
            borderRadius: 999,
          }}
        >
          daily brief · {isSnapshot ? "snapshot" : "live"}
        </span>
        {isGemini && (
          <span
            title="Thesis text generated by Gemini, grounded on indicator values"
            style={{
              fontFamily: "'JetBrains Mono', monospace",
              fontSize: 10, letterSpacing: 1.2, textTransform: "uppercase",
              color: "#A78BFA",
              padding: "4px 10px",
              border: "1px solid rgba(167,139,250,0.4)",
              background: "rgba(167,139,250,0.08)",
              borderRadius: 999,
            }}
          >
            ✦ ai-written
          </span>
        )}
      </div>

      <div
        style={{
          display: "flex", alignItems: "center", gap: 8,
          fontFamily: "'JetBrains Mono', monospace",
        }}
      >
        <div
          style={{
            display: "flex", alignItems: "center", gap: 8,
            padding: "7px 12px",
            background: "var(--bg-elev)",
            border: "1px solid var(--border)",
            borderRadius: 8,
            fontSize: 12, color: "var(--fg-muted)",
          }}
        >
          <span style={{ width: 6, height: 6, borderRadius: 999, background: "#22D3A4", boxShadow: "0 0 8px #22D3A4AA" }} />
          NSE · {snapshotDate}
        </div>
        {onRefresh && (
          <IconButton aria-label="Refresh" onClick={onRefresh} disabled={refreshing}>
            <Icon name="refresh" size={15} style={{
              animation: refreshing ? "spin 0.8s linear infinite" : "none",
            }} />
          </IconButton>
        )}
        <IconButton aria-label="Toggle theme" onClick={onToggleTheme}>
          <Icon name={dark ? "sun" : "moon"} size={15} />
        </IconButton>
      </div>
    </nav>
  );
};

const Logo = () => (
  <div
    style={{
      display: "inline-flex", alignItems: "center", gap: 10,
      fontFamily: "'JetBrains Mono', monospace",
    }}
  >
    <span
      style={{
        display: "inline-flex", alignItems: "center", justifyContent: "center",
        width: 28, height: 28, borderRadius: 8,
        background: "linear-gradient(135deg, #A78BFA, #7DD3FC)",
        color: "#0A0A0B", fontWeight: 700, fontSize: 16,
        letterSpacing: -0.5,
      }}
    >
      <svg width="14" height="14" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2.5" strokeLinecap="round" strokeLinejoin="round">
        <path d="M4 16 L10 10 L14 14 L20 6" />
        <path d="M14 6 L20 6 L20 12" />
      </svg>
    </span>
    <span style={{ fontSize: 18, fontWeight: 600, letterSpacing: -0.3, color: "var(--fg)" }}>
      tilt
    </span>
  </div>
);

const IconButton = ({ children, onClick, "aria-label": label, disabled }) => (
  <button
    onClick={onClick}
    aria-label={label}
    disabled={disabled}
    style={{
      width: 34, height: 34,
      display: "inline-flex", alignItems: "center", justifyContent: "center",
      background: "transparent", border: "1px solid var(--border)",
      borderRadius: 8, color: "var(--fg-muted)",
      cursor: disabled ? "not-allowed" : "pointer",
      opacity: disabled ? 0.6 : 1,
    }}
    onMouseEnter={(e) => {
      if (disabled) return;
      e.currentTarget.style.background = "var(--bg-elev)";
      e.currentTarget.style.color = "var(--fg)";
    }}
    onMouseLeave={(e) => {
      e.currentTarget.style.background = "transparent";
      e.currentTarget.style.color = "var(--fg-muted)";
    }}
  >
    {children}
  </button>
);

window.TopNav = TopNav;
